---
- name: "Customizing Parrot"
  hosts: localhost
  connection: local
  roles:
    - role: "roles/configure-tmux"
    - role: "roles/customize-terminal"
    - role: "roles/configure-nvim"
    #    - role: "roles/install-tools"
    #    - role: "roles/customize-browser"
